version: "3.2"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "3000:3000"
    restart: always
    volumes:
      - ./ci.conf:/etc/nginx/conf.d/ci.conf
      
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://gitea:3000
    restart: always
    volumes:
      - ./gitea:/data

  drone:
    image: drone/drone:1
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_SERVER_HOST=drone
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET
      - DRONE_GITEA_CLIENT_ID
      - DRONE_GITEA_CLIENT_SECRET
      - DRONE_USER_CREATE
    restart: always
    volumes:
      - ./drone:/data

  drone-runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-runner
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        
